//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class CheckPoseRequest : Message
    {
        public const string RosMessageName = "robotics_demo/CheckPose";

        public QuaternionProprioState QuatPos;

        public CheckPoseRequest()
        {
            this.QuatPos = new QuaternionProprioState();
        }

        public CheckPoseRequest(QuaternionProprioState QuatPos)
        {
            this.QuatPos = QuatPos;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(QuatPos.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.QuatPos.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "CheckPoseRequest: " +
            "\nQuatPos: " + QuatPos.ToString();
        }
    }
}
