//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class findIKRequest : Message
    {
        public const string RosMessageName = "robotics_demo/findIK";

        public PositionCommand position;

        public findIKRequest()
        {
            this.position = new PositionCommand();
        }

        public findIKRequest(PositionCommand position)
        {
            this.position = position;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(position.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.position.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "findIKRequest: " +
            "\nposition: " + position.ToString();
        }
    }
}
