//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class findIKResponse : Message
    {
        public const string RosMessageName = "robotics_demo/findIK";

        public JointPositions act;

        public findIKResponse()
        {
            this.act = new JointPositions();
        }

        public findIKResponse(JointPositions act)
        {
            this.act = act;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(act.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.act.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "findIKResponse: " +
            "\nact: " + act.ToString();
        }
    }
}
