//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class AchievedGoal : Message
    {
        public const string RosMessageName = "robotics_demo/AchievedGoal";

        public float obj1_pos_x;
        public float obj1_pos_y;
        public float obj1_pos_z;
        public float obj1_q1;
        public float obj1_q2;
        public float obj1_q3;
        public float obj1_q4;

        public AchievedGoal()
        {
            this.obj1_pos_x = 0.0f;
            this.obj1_pos_y = 0.0f;
            this.obj1_pos_z = 0.0f;
            this.obj1_q1 = 0.0f;
            this.obj1_q2 = 0.0f;
            this.obj1_q3 = 0.0f;
            this.obj1_q4 = 0.0f;
        }

        public AchievedGoal(float obj1_pos_x, float obj1_pos_y, float obj1_pos_z, float obj1_q1, float obj1_q2, float obj1_q3, float obj1_q4)
        {
            this.obj1_pos_x = obj1_pos_x;
            this.obj1_pos_y = obj1_pos_y;
            this.obj1_pos_z = obj1_pos_z;
            this.obj1_q1 = obj1_q1;
            this.obj1_q2 = obj1_q2;
            this.obj1_q3 = obj1_q3;
            this.obj1_q4 = obj1_q4;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.obj1_pos_x));
            listOfSerializations.Add(BitConverter.GetBytes(this.obj1_pos_y));
            listOfSerializations.Add(BitConverter.GetBytes(this.obj1_pos_z));
            listOfSerializations.Add(BitConverter.GetBytes(this.obj1_q1));
            listOfSerializations.Add(BitConverter.GetBytes(this.obj1_q2));
            listOfSerializations.Add(BitConverter.GetBytes(this.obj1_q3));
            listOfSerializations.Add(BitConverter.GetBytes(this.obj1_q4));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.obj1_pos_x = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.obj1_pos_y = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.obj1_pos_z = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.obj1_q1 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.obj1_q2 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.obj1_q3 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.obj1_q4 = BitConverter.ToSingle(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "AchievedGoal: " +
            "\nobj1_pos_x: " + obj1_pos_x.ToString() +
            "\nobj1_pos_y: " + obj1_pos_y.ToString() +
            "\nobj1_pos_z: " + obj1_pos_z.ToString() +
            "\nobj1_q1: " + obj1_q1.ToString() +
            "\nobj1_q2: " + obj1_q2.ToString() +
            "\nobj1_q3: " + obj1_q3.ToString() +
            "\nobj1_q4: " + obj1_q4.ToString();
        }
    }
}
