//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class FullState : Message
    {
        public const string RosMessageName = "robotics_demo/FullState";

        public float base_link;
        public float shoulder_link;
        public float upper_arm_link;
        public float forearm_link;
        public float wrist_1_link;
        public float wrist_2_link;
        public float wrist_3_link;
        public float ee_link;
        public float grasptarget;
        public float tool0;
        public float robotiq_arg2f_base_link;
        public float left_outer_knuckle;
        public float left_outer_finger;
        public float left_inner_finger;
        public float left_inner_finger_pad;
        public float left_inner_knuckle;
        public float right_outer_knuckle;
        public float right_outer_finger;
        public float right_inner_finger;
        public float right_inner_finger_pad;
        public float right_inner_knuckle;
        public Sensor.Image shoulderImage;
        public Sensor.Image gripperImage;
        public float arm_pos_x;
        public float arm_pos_y;
        public float arm_pos_z;
        public float arm_q1;
        public float arm_q2;
        public float arm_q3;
        public float arm_q4;
        public float gripper;
        public float obj1_pos_x;
        public float obj1_pos_y;
        public float obj1_pos_z;
        public float obj1_q1;
        public float obj1_q2;
        public float obj1_q3;
        public float obj1_q4;

        public FullState()
        {
            this.base_link = 0.0f;
            this.shoulder_link = 0.0f;
            this.upper_arm_link = 0.0f;
            this.forearm_link = 0.0f;
            this.wrist_1_link = 0.0f;
            this.wrist_2_link = 0.0f;
            this.wrist_3_link = 0.0f;
            this.ee_link = 0.0f;
            this.grasptarget = 0.0f;
            this.tool0 = 0.0f;
            this.robotiq_arg2f_base_link = 0.0f;
            this.left_outer_knuckle = 0.0f;
            this.left_outer_finger = 0.0f;
            this.left_inner_finger = 0.0f;
            this.left_inner_finger_pad = 0.0f;
            this.left_inner_knuckle = 0.0f;
            this.right_outer_knuckle = 0.0f;
            this.right_outer_finger = 0.0f;
            this.right_inner_finger = 0.0f;
            this.right_inner_finger_pad = 0.0f;
            this.right_inner_knuckle = 0.0f;
            this.shoulderImage = new Sensor.Image();
            this.gripperImage = new Sensor.Image();
            this.arm_pos_x = 0.0f;
            this.arm_pos_y = 0.0f;
            this.arm_pos_z = 0.0f;
            this.arm_q1 = 0.0f;
            this.arm_q2 = 0.0f;
            this.arm_q3 = 0.0f;
            this.arm_q4 = 0.0f;
            this.gripper = 0.0f;
            this.obj1_pos_x = 0.0f;
            this.obj1_pos_y = 0.0f;
            this.obj1_pos_z = 0.0f;
            this.obj1_q1 = 0.0f;
            this.obj1_q2 = 0.0f;
            this.obj1_q3 = 0.0f;
            this.obj1_q4 = 0.0f;
        }

        public FullState(float base_link, float shoulder_link, float upper_arm_link, float forearm_link, float wrist_1_link, float wrist_2_link, float wrist_3_link, float ee_link, float grasptarget, float tool0, float robotiq_arg2f_base_link, float left_outer_knuckle, float left_outer_finger, float left_inner_finger, float left_inner_finger_pad, float left_inner_knuckle, float right_outer_knuckle, float right_outer_finger, float right_inner_finger, float right_inner_finger_pad, float right_inner_knuckle, Sensor.Image shoulderImage, Sensor.Image gripperImage, float arm_pos_x, float arm_pos_y, float arm_pos_z, float arm_q1, float arm_q2, float arm_q3, float arm_q4, float gripper, float obj1_pos_x, float obj1_pos_y, float obj1_pos_z, float obj1_q1, float obj1_q2, float obj1_q3, float obj1_q4)
        {
            this.base_link = base_link;
            this.shoulder_link = shoulder_link;
            this.upper_arm_link = upper_arm_link;
            this.forearm_link = forearm_link;
            this.wrist_1_link = wrist_1_link;
            this.wrist_2_link = wrist_2_link;
            this.wrist_3_link = wrist_3_link;
            this.ee_link = ee_link;
            this.grasptarget = grasptarget;
            this.tool0 = tool0;
            this.robotiq_arg2f_base_link = robotiq_arg2f_base_link;
            this.left_outer_knuckle = left_outer_knuckle;
            this.left_outer_finger = left_outer_finger;
            this.left_inner_finger = left_inner_finger;
            this.left_inner_finger_pad = left_inner_finger_pad;
            this.left_inner_knuckle = left_inner_knuckle;
            this.right_outer_knuckle = right_outer_knuckle;
            this.right_outer_finger = right_outer_finger;
            this.right_inner_finger = right_inner_finger;
            this.right_inner_finger_pad = right_inner_finger_pad;
            this.right_inner_knuckle = right_inner_knuckle;
            this.shoulderImage = shoulderImage;
            this.gripperImage = gripperImage;
            this.arm_pos_x = arm_pos_x;
            this.arm_pos_y = arm_pos_y;
            this.arm_pos_z = arm_pos_z;
            this.arm_q1 = arm_q1;
            this.arm_q2 = arm_q2;
            this.arm_q3 = arm_q3;
            this.arm_q4 = arm_q4;
            this.gripper = gripper;
            this.obj1_pos_x = obj1_pos_x;
            this.obj1_pos_y = obj1_pos_y;
            this.obj1_pos_z = obj1_pos_z;
            this.obj1_q1 = obj1_q1;
            this.obj1_q2 = obj1_q2;
            this.obj1_q3 = obj1_q3;
            this.obj1_q4 = obj1_q4;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.base_link));
            listOfSerializations.Add(BitConverter.GetBytes(this.shoulder_link));
            listOfSerializations.Add(BitConverter.GetBytes(this.upper_arm_link));
            listOfSerializations.Add(BitConverter.GetBytes(this.forearm_link));
            listOfSerializations.Add(BitConverter.GetBytes(this.wrist_1_link));
            listOfSerializations.Add(BitConverter.GetBytes(this.wrist_2_link));
            listOfSerializations.Add(BitConverter.GetBytes(this.wrist_3_link));
            listOfSerializations.Add(BitConverter.GetBytes(this.ee_link));
            listOfSerializations.Add(BitConverter.GetBytes(this.grasptarget));
            listOfSerializations.Add(BitConverter.GetBytes(this.tool0));
            listOfSerializations.Add(BitConverter.GetBytes(this.robotiq_arg2f_base_link));
            listOfSerializations.Add(BitConverter.GetBytes(this.left_outer_knuckle));
            listOfSerializations.Add(BitConverter.GetBytes(this.left_outer_finger));
            listOfSerializations.Add(BitConverter.GetBytes(this.left_inner_finger));
            listOfSerializations.Add(BitConverter.GetBytes(this.left_inner_finger_pad));
            listOfSerializations.Add(BitConverter.GetBytes(this.left_inner_knuckle));
            listOfSerializations.Add(BitConverter.GetBytes(this.right_outer_knuckle));
            listOfSerializations.Add(BitConverter.GetBytes(this.right_outer_finger));
            listOfSerializations.Add(BitConverter.GetBytes(this.right_inner_finger));
            listOfSerializations.Add(BitConverter.GetBytes(this.right_inner_finger_pad));
            listOfSerializations.Add(BitConverter.GetBytes(this.right_inner_knuckle));
            listOfSerializations.AddRange(shoulderImage.SerializationStatements());
            listOfSerializations.AddRange(gripperImage.SerializationStatements());
            listOfSerializations.Add(BitConverter.GetBytes(this.arm_pos_x));
            listOfSerializations.Add(BitConverter.GetBytes(this.arm_pos_y));
            listOfSerializations.Add(BitConverter.GetBytes(this.arm_pos_z));
            listOfSerializations.Add(BitConverter.GetBytes(this.arm_q1));
            listOfSerializations.Add(BitConverter.GetBytes(this.arm_q2));
            listOfSerializations.Add(BitConverter.GetBytes(this.arm_q3));
            listOfSerializations.Add(BitConverter.GetBytes(this.arm_q4));
            listOfSerializations.Add(BitConverter.GetBytes(this.gripper));
            listOfSerializations.Add(BitConverter.GetBytes(this.obj1_pos_x));
            listOfSerializations.Add(BitConverter.GetBytes(this.obj1_pos_y));
            listOfSerializations.Add(BitConverter.GetBytes(this.obj1_pos_z));
            listOfSerializations.Add(BitConverter.GetBytes(this.obj1_q1));
            listOfSerializations.Add(BitConverter.GetBytes(this.obj1_q2));
            listOfSerializations.Add(BitConverter.GetBytes(this.obj1_q3));
            listOfSerializations.Add(BitConverter.GetBytes(this.obj1_q4));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.base_link = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.shoulder_link = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.upper_arm_link = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.forearm_link = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.wrist_1_link = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.wrist_2_link = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.wrist_3_link = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.ee_link = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.grasptarget = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.tool0 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.robotiq_arg2f_base_link = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.left_outer_knuckle = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.left_outer_finger = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.left_inner_finger = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.left_inner_finger_pad = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.left_inner_knuckle = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.right_outer_knuckle = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.right_outer_finger = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.right_inner_finger = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.right_inner_finger_pad = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.right_inner_knuckle = BitConverter.ToSingle(data, offset);
            offset += 4;
            offset = this.shoulderImage.Deserialize(data, offset);
            offset = this.gripperImage.Deserialize(data, offset);
            this.arm_pos_x = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.arm_pos_y = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.arm_pos_z = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.arm_q1 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.arm_q2 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.arm_q3 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.arm_q4 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.gripper = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.obj1_pos_x = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.obj1_pos_y = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.obj1_pos_z = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.obj1_q1 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.obj1_q2 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.obj1_q3 = BitConverter.ToSingle(data, offset);
            offset += 4;
            this.obj1_q4 = BitConverter.ToSingle(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "FullState: " +
            "\nbase_link: " + base_link.ToString() +
            "\nshoulder_link: " + shoulder_link.ToString() +
            "\nupper_arm_link: " + upper_arm_link.ToString() +
            "\nforearm_link: " + forearm_link.ToString() +
            "\nwrist_1_link: " + wrist_1_link.ToString() +
            "\nwrist_2_link: " + wrist_2_link.ToString() +
            "\nwrist_3_link: " + wrist_3_link.ToString() +
            "\nee_link: " + ee_link.ToString() +
            "\ngrasptarget: " + grasptarget.ToString() +
            "\ntool0: " + tool0.ToString() +
            "\nrobotiq_arg2f_base_link: " + robotiq_arg2f_base_link.ToString() +
            "\nleft_outer_knuckle: " + left_outer_knuckle.ToString() +
            "\nleft_outer_finger: " + left_outer_finger.ToString() +
            "\nleft_inner_finger: " + left_inner_finger.ToString() +
            "\nleft_inner_finger_pad: " + left_inner_finger_pad.ToString() +
            "\nleft_inner_knuckle: " + left_inner_knuckle.ToString() +
            "\nright_outer_knuckle: " + right_outer_knuckle.ToString() +
            "\nright_outer_finger: " + right_outer_finger.ToString() +
            "\nright_inner_finger: " + right_inner_finger.ToString() +
            "\nright_inner_finger_pad: " + right_inner_finger_pad.ToString() +
            "\nright_inner_knuckle: " + right_inner_knuckle.ToString() +
            "\nshoulderImage: " + shoulderImage.ToString() +
            "\ngripperImage: " + gripperImage.ToString() +
            "\narm_pos_x: " + arm_pos_x.ToString() +
            "\narm_pos_y: " + arm_pos_y.ToString() +
            "\narm_pos_z: " + arm_pos_z.ToString() +
            "\narm_q1: " + arm_q1.ToString() +
            "\narm_q2: " + arm_q2.ToString() +
            "\narm_q3: " + arm_q3.ToString() +
            "\narm_q4: " + arm_q4.ToString() +
            "\ngripper: " + gripper.ToString() +
            "\nobj1_pos_x: " + obj1_pos_x.ToString() +
            "\nobj1_pos_y: " + obj1_pos_y.ToString() +
            "\nobj1_pos_z: " + obj1_pos_z.ToString() +
            "\nobj1_q1: " + obj1_q1.ToString() +
            "\nobj1_q2: " + obj1_q2.ToString() +
            "\nobj1_q3: " + obj1_q3.ToString() +
            "\nobj1_q4: " + obj1_q4.ToString();
        }
    }
}
