//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class ImageTest : Message
    {
        public const string RosMessageName = "robotics_demo/ImageTest";

        public Sensor.Image shoulderImage;
        public Sensor.Image gripperImage;

        public ImageTest()
        {
            this.shoulderImage = new Sensor.Image();
            this.gripperImage = new Sensor.Image();
        }

        public ImageTest(Sensor.Image shoulderImage, Sensor.Image gripperImage)
        {
            this.shoulderImage = shoulderImage;
            this.gripperImage = gripperImage;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(shoulderImage.SerializationStatements());
            listOfSerializations.AddRange(gripperImage.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.shoulderImage.Deserialize(data, offset);
            offset = this.gripperImage.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "ImageTest: " +
            "\nshoulderImage: " + shoulderImage.ToString() +
            "\ngripperImage: " + gripperImage.ToString();
        }
    }
}
