//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class Observation : Message
    {
        public const string RosMessageName = "robotics_demo/Observation";

        public QuaternionProprioState proprio;
        public AchievedGoal ag;
        public Sensor.Image shoulderImage;
        public Sensor.Image gripperImage;

        public Observation()
        {
            this.proprio = new QuaternionProprioState();
            this.ag = new AchievedGoal();
            this.shoulderImage = new Sensor.Image();
            this.gripperImage = new Sensor.Image();
        }

        public Observation(QuaternionProprioState proprio, AchievedGoal ag, Sensor.Image shoulderImage, Sensor.Image gripperImage)
        {
            this.proprio = proprio;
            this.ag = ag;
            this.shoulderImage = shoulderImage;
            this.gripperImage = gripperImage;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(proprio.SerializationStatements());
            listOfSerializations.AddRange(ag.SerializationStatements());
            listOfSerializations.AddRange(shoulderImage.SerializationStatements());
            listOfSerializations.AddRange(gripperImage.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.proprio.Deserialize(data, offset);
            offset = this.ag.Deserialize(data, offset);
            offset = this.shoulderImage.Deserialize(data, offset);
            offset = this.gripperImage.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "Observation: " +
            "\nproprio: " + proprio.ToString() +
            "\nag: " + ag.ToString() +
            "\nshoulderImage: " + shoulderImage.ToString() +
            "\ngripperImage: " + gripperImage.ToString();
        }
    }
}
