//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class ObsRequest : Message
    {
        public const string RosMessageName = "robotics_demo/ObsRequest";

        public int timestep;
        public double time;

        public ObsRequest()
        {
            this.timestep = 0;
            this.time = 0.0;
        }

        public ObsRequest(int timestep, double time)
        {
            this.timestep = timestep;
            this.time = time;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.timestep));
            listOfSerializations.Add(BitConverter.GetBytes(this.time));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.timestep = BitConverter.ToInt32(data, offset);
            offset += 4;
            this.time = BitConverter.ToDouble(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "ObsRequest: " +
            "\ntimestep: " + timestep.ToString() +
            "\ntime: " + time.ToString();
        }
    }
}
