//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class ReplayInfo : Message
    {
        public const string RosMessageName = "robotics_demo/ReplayInfo";

        public RPYState resetState;
        public Std.Float32MultiArray acts;

        public ReplayInfo()
        {
            this.resetState = new RPYState();
            this.acts = new Std.Float32MultiArray();
        }

        public ReplayInfo(RPYState resetState, Std.Float32MultiArray acts)
        {
            this.resetState = resetState;
            this.acts = acts;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(resetState.SerializationStatements());
            listOfSerializations.AddRange(acts.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.resetState.Deserialize(data, offset);
            offset = this.acts.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "ReplayInfo: " +
            "\nresetState: " + resetState.ToString() +
            "\nacts: " + acts.ToString();
        }
    }
}
