//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class ResetInfo : Message
    {
        public const string RosMessageName = "robotics_demo/ResetInfo";

        public JointPositions joints;
        public AchievedGoal ag;

        public ResetInfo()
        {
            this.joints = new JointPositions();
            this.ag = new AchievedGoal();
        }

        public ResetInfo(JointPositions joints, AchievedGoal ag)
        {
            this.joints = joints;
            this.ag = ag;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(joints.SerializationStatements());
            listOfSerializations.AddRange(ag.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.joints.Deserialize(data, offset);
            offset = this.ag.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "ResetInfo: " +
            "\njoints: " + joints.ToString() +
            "\nag: " + ag.ToString();
        }
    }
}
