//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class RPYState : Message
    {
        public const string RosMessageName = "robotics_demo/RPYState";

        public RPYProprioState proprio;
        public AchievedGoal ag;

        public RPYState()
        {
            this.proprio = new RPYProprioState();
            this.ag = new AchievedGoal();
        }

        public RPYState(RPYProprioState proprio, AchievedGoal ag)
        {
            this.proprio = proprio;
            this.ag = ag;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(proprio.SerializationStatements());
            listOfSerializations.AddRange(ag.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.proprio.Deserialize(data, offset);
            offset = this.ag.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "RPYState: " +
            "\nproprio: " + proprio.ToString() +
            "\nag: " + ag.ToString();
        }
    }
}
