//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboticsDemo
{
    public class TransitionTuple : Message
    {
        public const string RosMessageName = "robotics_demo/TransitionTuple";

        public FullState o;
        public PositionCommand a;
        public double data_arrival_time;
        public double model_processed_time;

        public TransitionTuple()
        {
            this.o = new FullState();
            this.a = new PositionCommand();
            this.data_arrival_time = 0.0;
            this.model_processed_time = 0.0;
        }

        public TransitionTuple(FullState o, PositionCommand a, double data_arrival_time, double model_processed_time)
        {
            this.o = o;
            this.a = a;
            this.data_arrival_time = data_arrival_time;
            this.model_processed_time = model_processed_time;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(o.SerializationStatements());
            listOfSerializations.AddRange(a.SerializationStatements());
            listOfSerializations.Add(BitConverter.GetBytes(this.data_arrival_time));
            listOfSerializations.Add(BitConverter.GetBytes(this.model_processed_time));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.o.Deserialize(data, offset);
            offset = this.a.Deserialize(data, offset);
            this.data_arrival_time = BitConverter.ToDouble(data, offset);
            offset += 8;
            this.model_processed_time = BitConverter.ToDouble(data, offset);
            offset += 8;

            return offset;
        }

        public override string ToString()
        {
            return "TransitionTuple: " +
            "\no: " + o.ToString() +
            "\na: " + a.ToString() +
            "\ndata_arrival_time: " + data_arrival_time.ToString() +
            "\nmodel_processed_time: " + model_processed_time.ToString();
        }
    }
}
